name: GCP Final Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code
        uses: actions/checkout@v3

      - name: Login to docker
        run: echo "${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin

      - name: Build Docker Image
        run: docker build -t premchandpamidi/test:latest .

      - name: Pushing into docker hub
        run: docker push premchandpamidi/test:latest

      - name: Deploy to GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.GCP_HOST}}
          username: ${{secrets.GCP_USER}}
          key: ${{secrets.GCP_KEY}}
          script: |
            docker pull premchandpamidi/test:latest
            docker rm -f test-app || true
            docker run -d --name test-app -p 8095:80 premchandpamidi/test:latest
